plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.5'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'jacoco'
}

group = 'apap.ti.2025'
version = '0.0.1-SNAPSHOT'
description = 'Tugas Individu APAP 2306240156 - Tour Package Back End'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	runtimeOnly 'com.h2database:h2'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testImplementation 'org.hamcrest:hamcrest:2.2'
	implementation('com.github.javafaker:javafaker:1.0.2') {
		exclude group: 'org.yaml', module: 'snakeyaml'
	}
	testImplementation 'org.springframework.security:spring-security-test'
	implementation 'com.fasterxml.jackson.core:jackson-databind'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'jakarta.xml.bind:jakarta.xml.bind-api-parent:4.0.2'
	implementation 'org.glassfish.jaxb:jaxb-runtime:4.0.5'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'
	implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
	implementation 'jakarta.xml.bind:jakarta.xml.bind-api:4.0.2'
	testImplementation 'org.mockito:mockito-core'

}

tasks.named('test') {
    useJUnitPlatform()
    ignoreFailures = true
    finalizedBy tasks.jacocoTestReport // pastikan pakai tasks. agar Gradle tahu dependensi task-nya
}

jacoco {
    toolVersion = "0.8.10"
}

jacocoTestReport {
    dependsOn tasks.test
    executionData fileTree(dir: "$buildDir/jacoco", include: "**/*.exec")
    reports {
        xml.required = true
        csv.required = false
        html.required = true // ✅ WAJIB ada supaya file index.html dibuat
        html.outputLocation = layout.buildDirectory.dir("reports/jacoco/test/html") // lokasi report
    }
}
