spring:
  datasource:
    url: jdbc:postgresql://54.86.132.65:35002/TourPackage-2306240156
    username: travelapap
    password: 2306240156

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


