apiVersion: v1
kind: Secret
metadata:
  name: tourpackage-be-secret
  namespace: default
type: Opaque
stringData:
  # Database Password
  DATABASE_PASSWORD: "2306240156"
  CORS_ALLOWED_ORIGINS: "http://2306240156-fe.hafizmuh.site,https://2306240156-fe.hafizmuh.site,http://2306275166-fe.hafizmuh.site,https://2306275166-fe.hafizmuh.site"
  
  # Bill Service Integration - API Keys
  # Bill Service → Tour Package (Payment Callback)
  API_KEY_BILL_SERVICE: "NlfUxKNkXIwORhKZCbbYevFecxRCFttNnycTS"
  
  # Tour Package → Bill Service (Create Bill)
  BILL_SERVICE_API_KEY: "GWJBdjIkKAYlYsMthrgILglcAcVwLJRudC"
